version: "3.9"

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - litellm_ai-network

volumes:
  ollama:

networks:
  litellm_ai-network:
    external: true
